### ISSUE TITLE
komputeko offline forever?

### ISSUE THREAD

**Issue by notklaatu** [LaPingvino/komputeko-data-malnova#3]
Is komputeko.net gone forever? is this related to it at all?

If so, would hosting be helpful? I have a server and space on it; glad to offer free hosting.

**Comment by LaPingvino** [comment]
ĝi jam revenis, cetere kodo mia ne estas de la nuna sed por eventuala venonta versio de komputeko, por kiu mi ne vere trovas tempon...

**Comment by notklaatu** [comment]
Bona! Mi amas la retpaĝaron kaj ĉiutaga uzas ĝin.
